#!/bin/bash
# syuscript 2024-07-21
# dependencies: rebuild-detector >(checkrebuild) 'supplied script' >(overdue)
# https://bbs.archlinux.org/viewtopic.php?id=246036
# https://bbs.archlinux.org/viewtopic.php?id=132322

bold='\033[1m'
cyan='\033[0;96m'
yellow="\033[0;93m"
none='\033[00m'

[[ ! -d ${HOME}/pacman-update-logs/ ]] && mkdir -p "${HOME}/pacman-update-logs/"

Filedate=$(find "${HOME}"/Desktop/prep4ud.dir/ -type f -printf "%f\n" 2>/dev/null | sort -V | tail -1)

	find "${HOME}"/pacman-update-logs/* -maxdepth 0 -type f | 
	sort  |  head -n -4  |  xargs rm -f								# Maintain 5 logs

	echo; echo -e "${cyan} ${bold}  Contents of prep4ud report ${Filedate}: ${none}"; echo

	cat "${HOME}"/Desktop/prep4ud.dir/"${Filedate}" 2>/dev/null || { echo "  Prep4ud report NA."; }

	echo; echo -e "${cyan}${bold}  Running pacman -Syu.... ${none}"; echo

	sudo pacman -Syu --color=always |& tee "${HOME}/pacman-update-logs/$(date '+%Y-%m-%d').log"

	echo; echo -e "${cyan}${bold}  Checking kernel update.... ${none}"

	modules=$(find /usr/lib/modules -maxdepth 1 -printf "%f\n" | grep -v modules | sort | tail -n1)

	[[ $modules != $(uname -r) ]] && echo -e "${yellow}${bold}  Kernel was updated.${none}"
	[[ $modules == $(uname -r) ]] && echo "  Kernel was not updated."

if	lsof 2>/dev/null | grep -q 'DEL.*lib' ; then

	echo; echo -e "${cyan}${bold}  Running overdue script..... ${none}"
	sudo "$(which overdue)"

	echo; echo -e "${cyan}${bold}  Running checkrebuild....${none} No output indicates no action needed."
	checkrebuild -v

    else
	echo; echo -e "${cyan}${bold}  No need to restart ${none}"
fi
	echo; echo -e "${cyan}${bold}  To clean pacman cache run: ${none}"
	echo "  paccache --cachedir /var/cache/pacman/pkg/ --uninstalled --remove "
	echo "  paccache --cachedir /var/cache/pacman/pkg/ --remove --keep 2 "

	echo; echo -e "${cyan}${bold}  Review pacman log for this update: ${none}"
	echo "  cat ${HOME}/pacman-update-logs/$(date '+%Y-%m-%d').log"
	echo
